version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - id: lx-windows
    main: ./cmd/lx
    binary: lx
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: zip
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: andre-carbajal
    name: lx
  draft: false
  prerelease: auto
